name: Flutter - Android Build Dev

on: 
  push: 
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0-13.0.pre'
          channel: 'master'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test
  


        